### PR TITLE
Fix anonymous access for other registries

### LINKED ISSUE #68: Support anonymous acces to non-docker-hub registries
When no auth params are provided we currently check whether the specified registry is the default one (docker hub) and if so, create an anonymous token and use it for other queries.
https://github.com/awakesecurity/hocker/blob/be62882b49cd2ad5b108d951eb67fe2c6bb36244/src/Network/Wreq/Docker/Registry.hs#L94-L100
However, this is also required for other non-docker-hub registries as well. More, the URL shouldn't be hardcoded like this, but we should do a simple query to the registry and if it returns 401, check the `WWW-Authenticate` header with the info where to get the token.

>Under the Registry V2 workflow, clients should contact the registry first. If the registry server requires authentication it will return a 401 Unauthorized response with a WWW-Authenticate header detailing how to authenticate to this registry.

https://docs.docker.com/reference/api/registry/auth/#how-to-authenticate

I'll try to prepare fix for this

### PR DESCRIPTION
**Pull request by tm-drtina**
This should allow anonymous access to other registries than Docker Hub by parsing `WWW-Authenticate` header instead of havin hardcoded URLs for hub.

The parser is done according to RFC7235
https://datatracker.ietf.org/doc/html/rfc7235#autoid-30

Closes #68 

##### Google Container/Artifact Registry
```
$ curl --dump-header - https://gcr.io/v2/distroless/nodejs/manifests/latest 
HTTP/2 200 
content-length: 741
content-type: application/vnd.docker.distribution.manifest.list.v2+json
docker-content-digest: sha256:b534f9b5528e69baa7e8caf7bcc1d93ecf59faa15d289221decf5889a2ed3877
docker-distribution-api-version: registry/2.0
x-gcr-using-artifact-registry: true
server: Docker Registry

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [ ... ]
}
```
##### Docker Hub
```
$ curl --dump-header - https://registry-1.docker.io/v2/library/node/manifests/latest 
HTTP/2 401 
content-type: application/json
content-length: 155
docker-distribution-api-version: registry/2.0
www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/node:pull"

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"library/node","Action":"pull"}]}]}
```

##### Google Container/Artifact Registry
```
$ cabal run hocker-manifest -- --registry https://gcr.io distroless/nodejs latest
{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"mediaType":"application/vnd.docker.container.image.v1+json","size":967,"digest":"sha256:cf46b336f6597ef45686d6f517a12c43466b85fbdff5cff01ff7d8109db47046"},"layers":[...]}
```
##### Docker Hub
```
$ cabal run hocker-manifest -- library/node latest
{"manifests":[...],"mediaType":"application\/vnd.oci.image.index.v1+json","schemaVersion":2}
```

### CODE REVIEW

File: src/Hocker/Types/AuthInfo.hs [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+  let sepByAtLeastComma = (ows >> char ',' >> (munch (\c -> isWhitespace c || c == ',')))
+  cs <- sepBy1 challenge sepByAtLeastComma
+  -- It can also end with "empty" challenges
+  _ <- many $ (char ',' >> ows)
+  return cs
+
+parseChallenges :: String -> Either HockerException [Challenge]
+parseChallenges headerVal = 
+  case readP_to_S (challenges <* eof) headerVal of
+    ((result, "") : _) -> Right result
```
Comment (kiara-riley) [inline src/Hocker/Types/AuthInfo.hs]: Wouldnt we want this to not multiple possible parses work? Or at least choose the result we want?

`((result, "") : [])`?

File: src/Hocker/Types/AuthInfo.hs [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+  AuthInfo(..),
+  parseWWWAuthHeader
+) where
+
+import           Control.Applicative          ((<|>))
+import qualified Data.ByteString.Char8        as C8
+import qualified Data.CaseInsensitive         as CI
+import           Data.Char                    (isAlphaNum, ord)
+import           Data.Maybe                   (listToMaybe, mapMaybe)
+import           URI.ByteString
```
Comment (jsoo1) [inline src/Hocker/Types/AuthInfo.hs]: My preference is to import qualified whenever possible. Up to you - I can't remember what the idiom in this repo is.

File: src/Hocker/Types/AuthInfo.hs [hunk 3]
```diff
@@ -0,0 +1,175 @@
...
+            | otherwise = case params c of
+                AuthParamsArr ps -> do
+                  rawRealm <- C8.pack <$> lookup (CI.mk "realm") ps
+                  service  <- C8.pack <$> lookup (CI.mk "service") ps
+                  scope    <- C8.pack <$> lookup (CI.mk "scope") ps
+
+                  realm <- either (\_ -> Nothing) Just $ parseURI strictURIParserOptions rawRealm
+                  pure AuthInfo{ realm, service, scope }
+                
+                AuthParamsB64 _ -> Nothing -- Not supported for now
```
Comment (jsoo1) [inline src/Hocker/Types/AuthInfo.hs]: I recommend this so that the parse errors can be propagated from the missing `bearer` token.

```suggestion
  authScheme <- listToMaybe <$> traverse transform parsedChallenges
  
  maybe notFoundErr Right authScheme
        where
          notFoundErr = Left $ hockerException "Unable to extract AuthInfo from WWW-Authentication header"
          transform c
            | scheme c /= AuthScheme (CI.mk "bearer") = Left (hockerException "not a bearer token")
            | otherwise = case params c of
                AuthParamsArr ps -> do
                  rawRealm <- C8.pack <$> lookup (CI.mk "realm") ps
                  service  <- C8.pack <$> lookup (CI.mk "service") ps
                  scope    <- C8.pack <$> lookup (CI.mk "scope") ps

                  realm <- first hockerException $ parseURI strictURIParserOptions rawRealm
                  pure AuthInfo{ realm, service, scope }
                AuthParamsB64 _ -> Left (hockerException "not supported")
```

File: src/Hocker/Types/AuthInfo.hs (hunk 1 above)
Comment (jsoo1) [reply src/Hocker/Types/AuthInfo.hs]: Also, would [readEither](https://hackage-content.haskell.org/package/base-4.22.0.0/docs/Text-Read.html#v:readEither) do the trick?

edit: Yes you could, if you implemented `Read` - which seems reasonable?

**Review by jsoo1 — COMMENTED** [review]
Thank you! This LGTM, but I would like some notes on testing done for this.

File: src/Hocker/Types/AuthInfo.hs (hunk 3 above)
Comment (tm-drtina) [reply src/Hocker/Types/AuthInfo.hs]: Wouldn't this error on non-bearer token? We are trying to find first (valid) bearer token

File: src/Hocker/Types/AuthInfo.hs (hunk 1 above)
Comment (tm-drtina) [reply src/Hocker/Types/AuthInfo.hs]: Can we get multiple parses when we specify EOF as the last parse?

I'll look into `Read`

File: src/Hocker/Types/AuthInfo.hs (hunk 2 above)
Comment (tm-drtina) [reply src/Hocker/Types/AuthInfo.hs]: Sure. I started implementing this in `Registry.hs` and split it later, so I only removed the unused imports. I shouldn't need everything from that module anyway

File: src/Hocker/Types/AuthInfo.hs (hunk 1 above)
Comment (kiara-riley) [reply src/Hocker/Types/AuthInfo.hs]: > Can we get multiple parses when we specify EOF as the last parse?

If you can't, it makes sense to make the pattern match specify that you only expect one parse.

Comment (tm-drtina) [reply src/Hocker/Types/AuthInfo.hs]: By switching to `Read` we got exactly that 👍 and it uncovered ambiguous parse when dealing with extra commas

**Comment by tm-drtina** [comment]
I've added some unit tests for the parser. I was testing it with Docker Hub registry and our internal one (both headers added to test cases, though obfuscated). Also checked gcr.io, but they allow anonymous access without tokens

**Comment by jsoo1** [comment]
> I've added some unit tests for the parser. I was testing it with Docker Hub registry and our internal one (both headers added to test cases, though obfuscated). Also checked gcr.io, but they allow anonymous access without tokens

If you wouldn't mind adding the manual tests done to the PR description, that would be excellent.

File: src/Hocker/Types/AuthInfo.hs [hunk 4]
```diff
@@ -0,0 +1,179 @@
...
+challenges = do
+  -- The header can start with an "empty" challenge
+  _ <- munch (\c -> isWhitespace c || c == ',')
+  let sepByAtLeastComma = (ows >> char ',' >> (munch (\c -> isWhitespace c || c == ',')))
+  cs <- sepBy1 challenge sepByAtLeastComma
+  -- It can also end with "empty" challenges
+  _ <- munch (\c -> isWhitespace c || c == ',')
+  return cs
+
+newtype WWWAuthHeader = WWWAuthHeader [Challenge]
```
Comment (jsoo1) [inline src/Hocker/Types/AuthInfo.hs]: Is there guaranteed to be at least one challenge? If so, how would you feel about making this a `NonEmpty Challenge`?

File: src/Hocker/Types/AuthInfo.hs (hunk 3 above)
Comment (jsoo1) [reply src/Hocker/Types/AuthInfo.hs]: Yes it would - you could also collect the errors up. I'm mostly concerned about throwing away useful info to the user, but this is not critical. Feel free to dismiss this if it makes sense.

File: src/Hocker/Types/AuthInfo.hs [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+  let authToken = AuthParamsB64 <$> token68
+  let authParams' = do
+        _   <- munch (\c -> isWhitespace c || c == ',')
+        res <- sepBy authParam (ows >> char ',' >> (munch (\c -> isWhitespace c || c == ',')))
+        pure $ AuthParamsArr res
+
+  authToken <|> authParams'
+
+-- challenge = auth-scheme [ 1*SP ( token68 / [ ( "," / auth-param ) *( OWS "," [ OWS auth-param ] ) ] ) ]
+challenge :: ReadP Challenge
```
Comment (jsoo1) [inline src/Hocker/Types/AuthInfo.hs:142]: Might be nice to implement `Read` for each of the parseable types.

**Review by jsoo1 — APPROVED** [review]
Thank you very much, no more blocking issues from me.

File: src/Hocker/Types/AuthInfo.hs (hunk 4 above)
Comment (jsoo1) [reply src/Hocker/Types/AuthInfo.hs]: Wait, the gcr.io example says no. Nevermind.

File: src/Hocker/Types/AuthInfo.hs (hunk 5 above)
Comment (tm-drtina) [reply src/Hocker/Types/AuthInfo.hs:142]: I'm not sure it's worth it. This is just a helper type and is not exported. More we never call the parse on this type, only the combined parser.
Some of the parsers affect each other (I was getting some ambiguous parses), so it only make sense to parse it as whole

File: src/Hocker/Types/AuthInfo.hs (hunk 4 above)
Comment (tm-drtina) [reply src/Hocker/Types/AuthInfo.hs]: Actually it is guaranteed by the RFC. If there are no challenges, the server shouldn't send the header. Though I'm not sure it's worth adding it
The gcr.io returns 200 OK, docker hub returns 401 with the header

File: src/Hocker/Types/AuthInfo.hs (hunk 3 above)
Comment (tm-drtina) [reply src/Hocker/Types/AuthInfo.hs]: I've added a change to collect the errors and combine them into a single error message. Also for the pattern match on errors I've changed the array to NonEmpty. I was calling there `sepBy1` anyway, so the parsing would fail on no items

**Review by jsoo1 — APPROVED** [review]
Reaffirming the approval. Thank you!
